# Generated by Django 2.0.5 on 2018-05-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=140)),
                ('date', models.DateTimeField()),
                ('vol1_dcm_path', models.CharField(max_length=500)),
                ('vol2_dcm_path', models.CharField(max_length=500)),
                ('vol_seg_dcm_path', models.CharField(max_length=500)),
            ],
        ),
    ]
